import os

os.system("export http_proxy=http://proxy.panasonic.com.sg:8080 https_proxy=http://proxy.panasonic.com.sg:8080")
os.system("youtube-dl -f 18 https://www.youtube.com/watch?v=Qso3QAYVKjs")
os.system("export http_proxy=http://proxy.panasonic.com.sg:8080 https_proxy=http://proxy.panasonic.com.sg:8080")
os.system("youtube-dl -f 18 https://www.youtube.com/watch?v=61o2OzMdC1U")
os.system("export http_proxy=http://proxy.panasonic.com.sg:8080 https_proxy=http://proxy.panasonic.com.sg:8080")
os.system("youtube-dl -f 18 https://www.youtube.com/watch?v=iKr0UMWh0a0")
os.system("export http_proxy=http://proxy.panasonic.com.sg:8080 https_proxy=http://proxy.panasonic.com.sg:8080")
os.system("youtube-dl -f 18 https://www.youtube.com/watch?v=TCTXWhFriuE&t=2232s")
os.system("export http_proxy=http://proxy.panasonic.com.sg:8080 https_proxy=http://proxy.panasonic.com.sg:8080")
os.system("youtube-dl -f 18 https://www.youtube.com/watch?v=9ErvnL7bmI4")

os.system("export http_proxy=http://proxy.panasonic.com.sg:8080 https_proxy=http://proxy.panasonic.com.sg:8080")
os.system("youtube-dl -f 18 https://www.youtube.com/watch?v=1hB_7K4cr5k")
os.system("export http_proxy=http://proxy.panasonic.com.sg:8080 https_proxy=http://proxy.panasonic.com.sg:8080")
os.system("youtube-dl -f 18 https://www.youtube.com/watch?v=6D2wuB5ED_E")
os.system("export http_proxy=http://proxy.panasonic.com.sg:8080 https_proxy=http://proxy.panasonic.com.sg:8080")
os.system("youtube-dl -f 18 https://www.youtube.com/watch?v=dwjhCizFWEI")
os.system("export http_proxy=http://proxy.panasonic.com.sg:8080 https_proxy=http://proxy.panasonic.com.sg:8080")
os.system("youtube-dl -f 18 https://www.youtube.com/watch?v=T4kR-DS4C5s")
